# /Users/benjaminfranklin/.config/tmuxinator/app.yml
name: app
root: ~/Documents/Code/Dext/application

windows:
  - vim:
  - git:
  - server:
      layout: tiled
      panes:
        - bin/rails server -p 3000
  - webpack:
      layout: tiled
      panes:
        - bin/yarn && HMR=true bin/webpack-dev-server
  - console:
      layout: tiled
      panes:
        - bin/rails c -- --nomultiline
  - sidekiq:
      layout: tiled
      panes:
        - bin/deploy/sidekiq
  - psql:
      layout: tiled
      panes:
        - psql receiptbank_development
  - cables:
      layout: main-vertical
      panes:
        - bin/anycable --log-grpc --debug --log-level=debug
        - anycable-go --host=localhost --port=3334 --headers="cookie,origin" --debug=true --log_level=debug
