" configure Vundle
filetype on " without this vim emits a zero exit status, later, because of :ft off
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  source ~/.vim/.vimrc.bundles
call vundle#end()

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

" A very general remap that several files may use down the line
let mapleader = " "
nnoremap SPACE <Nop>

source ~/.vim/.vimrc.libsettings
source ~/.vim/.vimrc.langsupport
source ~/.vim/.vimrc.keymaps
source ~/.vim/.vimrc.coc
" source ~/.vim/.vimrc.ycm
source ~/.vim/.vimrc.settings
source ~/.vim/.vimrc.appearance

" Vimdiff settings
if &diff                             " only for diff mode/vimdiff
  set diffopt=filler,context:1000000 " filler is default and inserts empty lines for sync
endif
