set nocompatible                                             " don't bother with vi compatibility
syntax enable                                                " enable syntax highlighting

" configure Vundle
filetype on " without this vim emits a zero exit status, later, because of :ft off
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  source ~/.vim/.vimrc.bundles
call vundle#end()

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

source ~/.vim/.vimrc.settings
source ~/.vim/.vimrc.keymaps
source ~/.vim/.vimrc.langsupport
source ~/.vim/.vimrc.appearance
source ~/.vim/.vimrc.libsettings

" Vimdiff settings
if &diff                             " only for diff mode/vimdiff
  set diffopt=filler,context:1000000 " filler is default and inserts empty lines for sync
endif
