#!/usr/bin/env zsh
alias sirb="irb --simple-prompt"
alias gotocode="cd ~/Documents/Code/"

# Git
alias gpr="git pull --rebase" # as in 'git pull rebase'
alias gfr="git fetch && git rebase" # as in 'git fetch and rebase"
alias gpp="gpr; git push --force-with-lease" # git pull --rebase; git push
alias gch="git checkout"
alias ga="git add"
alias gs="git status"
alias gd="git difftool"
alias gds="git difftool --staged"
alias gh="git log --graph --format=\"%C(bold blue)%h %C(white)| %s | %C(yellow)(%aN) %C(green)%cs\""
alias gsp="git stash pop"
alias gsa="git stash apply"
alias gsl="git stash list" 
alias gulc="git reset HEAD~1 --soft" # as in 'git undo last commit'
alias gr="git restore"

# Docker
alias dst="docker start"
alias dsp="docker stop"
alias dc="docker ps"
alias dr="docker run"
alias dcr="docker rm"
alias dir="docker rmi"
alias db="docker build"
alias di="docker images"
alias de="docker exec -t -i /bin/zsh"
alias dl="docker logs --tail 15"

gcm() {
	git commit -m "$@"
}

gstash() {
	git stash save "$@"
}

gunstage() {
	git restore --staged "$@"
}

