#!/usr/bin/env zsh
# Git
alias gf="git fetch"
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gup="git pull"
alias gupr="git pull --rebase"
alias gcm="git commit"
alias gst="scmpuff_status"
alias cgst="clear && gst"
alias gh="git log --graph --format=\"%C(bold blue)%h %C(white)| %s | %C(yellow)(%aN) %C(green)%cs\""
alias gs="git stash"
alias gsp="git stash pop"
alias gsa="git stash apply"
alias gsl="git stash list"

# Rake/Rails
alias rdm="bundle exec rake db:migrate db:test:prepare"
alias rdr="bundle exec rake db:rollback"
alias sirb="irb --simple-prompt"

# Yarn
alias yi="yarn install"
alias yt="yarn test"
alias ts="ts-node"

# Docker
alias dst="docker start"
alias dsp="docker stop"
alias dc="docker ps"
alias dr="docker run"
alias dcr="docker rm"
alias dir="docker rmi"
alias db="docker build"
alias di="docker images"
alias de="docker exec -t -i /bin/zsh"
alias dl="docker logs --tail 15"


