#!/usr/bin/env zsh

stty erase '^?'

eval "$(rbenv init - zsh)"
eval "$(jump shell)"
eval "$(scmpuff init -s)"

export EDITOR='vim'
export ZSH="$HOME/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
export TERM=xterm-256color
export GPG_TTY=$(tty)

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  zsh-autosuggestions
)

source ~/.zsh/aliases
source ~/.p10k.zsh
source $ZSH/oh-my-zsh.sh
source ~/.zsh/functions

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

forward () {
  ssh -R 8881:localhost:$1 -N -f root@134.122.84.33
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
