#!/usr/bin/env zsh

stty erase '^?'

eval "$(rbenv init - zsh)"
eval "$(jump shell)"
eval "$(scmpuff init -s)"

export EDITOR='vim'
export ZSH="$HOME/.oh-my-zsh"
export NVM_DIR="$HOME/.nvm"
export TERM=xterm-256color

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  zsh-autosuggestions
)

[[ -f ~/.zsh/aliases ]] && source ~/.zsh/aliases
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# Path to your oh-my-zsh installation.
source $ZSH/oh-my-zsh.sh

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

forward () {
  ssh -R 8881:localhost:$1 -N -f root@134.122.84.33
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
